### PR TITLE
Bump pre-commit dependencies

### PR DESCRIPTION
**Pull request by thecode**
Bump pre-commit dependencies by running `pre-commit autoupdate`

### CODE REVIEW

**Comment by frenck** [comment]
These are now out of sync with requirements_lint?

**Comment by thecode** [comment]
I have not found a way to make them in sync with `requirements_lint`, they constantly get out of sync, once dependabot will bump them they will probably be in sync for a short time.

**Comment by thecode** [comment]
Looking at `requirements_lint` with this PR they will be in sync (since all are bumped to latest), I will check if we can bump dependencies in pre-commit automatically or maybe use a different solution. (Now we use them in tox, on another repo I just run pre-commit in the CI step)

**Comment by frenck** [comment]
> I will check if we can bump dependencies in pre-commit automatically or maybe use a different solution

Alternatively, one could run the tool in pre-commit locally (instead of remote repos).

**Comment by thecode** [comment]
I went for an a GitHub workflow: https://github.com/home-assistant-libs/aiowebostv/pull/126

**Pull request closed without merging**
